version: '3.8'
services:
  springboot:
    image: devsree/spring-boot-mongo:3
    container_name: springboot
    ports:
    - 8080:8080
    environment:
    - MONGO_DB_HOSTNAME=mongo
    networks:
    - myspringnetwork
  mongo:
    image: mongo
    container_name: springboot-mongo
    volumes:
      - mongodb:/data/db
    networks:
    - myspringnetwork
volumes:
  mongodb:
    external: true
networks:
  myspringnetwork:
    external: true
